# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - nvm install 8
  - npm install netlify-cli -g
  - Rscript -e 'blogdown::install_hugo()'
  - sudo apt-get install -y fonts-roboto
  - fc-cache -fv
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'

script:
  - Rscript -e 'blogdown::build_site(method = "html")'
  - Rscript -e 'rmarkdown::render("static/directory/index.Rmd")'

deploy:
  provider: script
  script: netlify deploy -a $NETLIFY_KEY --dir=public
  skip_cleanup: true
