# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - npm install netlify-cli -g
  - Rscript -e 'blogdown::install_hugo()'
  - sudo apt-get install -y fonts-roboto libgeos-dev libgdal-dev libudunits2-dev
  - fc-cache -fv

script:
  # knit member directory before building site
  - Rscript -e 'knitr::knit("openplantpathology/OpenPlantPathology/static/directory/index.Rmd")'

  # import Roboto condensed
- Rscript -e 'hrbrthemes::import_roboto_condensed()'

  # build the website
  - Rscript -e 'blogdown::build_site(local = Sys.getenv("TRAVIS_PULL_REQUEST_BRANCH") != "")'

after_success:
  - ./deploy.sh
