# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial 
language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - pwd
  - go get -d github.com/netlify/netlifyctl
  - cd $GOPATH/src/github.com/netlify/netlifyctl
  - make deps build
  - go install
  - cd /home/travis/build/openplantpathology/OpenPlantPathology
  - sudo apt-get install -y fonts-roboto libjq-dev
  - Rscript -e 'install.packages(c(
                        "blogdown",
                        "hrbrthemes", 
                        "DT",
                        "devtools",
                        "flexdashboard",
                        "googleway",
                        "gsheet",
                        "kableExtra",
                        "leaflet",
                        "rmarkdown",
                        "magrittr",
                        "remotes",
                        "plotly",
                        "sessioninfo",
                        "tidyverse",
                        "viridis"))'
  - Rscript -e 'remotes::install_github("RLesur/klippy")'
  - Rscript -e 'blogdown::install_hugo()'
  - fc-cache -fv
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'
  - mkdir public

script:
  - Rscript -e 'blogdown::build_site(method = "html")'
  - Rscript -e 'rmarkdown::render("static/directory/index.Rmd")'

after_success:
-  sh deploy.sh
