# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - ./install_netlifyctl.sh
  - Rscript -e 'blogdown::install_hugo()'

script:
  - "Rscript -e 'blogdown::build_site()'"

after_success:
  - ./deploy.sh
