# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
    - $HOME/bin

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - "Rscript -e 'blogdown::build_site()'"
  - "Rscript -e 'blogdown::hugo_build()'"

after_success:
  - ./deploy.sh
  - cat  netlifyctl-debug.log

