# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
    - $HOME/bin

script:
  - "Rscript -e 'blogdown::install_hugo()'"
  
  # knit member directory before building site
  - "Rscript -e 'knitr::knit('./directory/index.Rmd')'"
  
  # build site
  - "Rscript -e 'blogdown::build_site()'"

after_success:
  - ./deploy.sh
  - cat netlifyctl-debug.log
