# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial 
language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm
  
addons:
  apt:
    packages:
      - fonts-roboto
      - libjq-dev
      - cargo

before_install:
  - nvm install 8
  - npm install netlify-cli -g
  - fc-cache -fv
  - mkdir public

script:
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'
  - Rscript -e 'blogdown::build_site()'

after_success:
-  sh deploy.sh
