# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial 
language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm
  
addons:
  apt:
    packages:
      - fonts-roboto
      - libjq-dev

before_install:
  - nvm install 8
  - npm install netlify-cli -g
  - Rscript -e 'install.packages(c(
                        "blogdown",
                        "hrbrthemes",
                        "DT",
                        "devtools",
                        "flexdashboard",
                        "googleway",
                        "gsheet",
                        "kableExtra",
                        "leaflet",
                        "rmarkdown",
                        "magrittr",
                        "remotes",
                        "plotly",
                        "sessioninfo",
                        "tidyverse",
                        "viridis"))'
  - Rscript -e 'remotes::install_github("RLesur/klippy")'
  - Rscript -e 'blogdown::install_hugo()'
  - fc-cache -fv
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'
  - mkdir public

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'
  - Rscript -e 'blogdown::build_site()'

after_success:
-  sh deploy.sh
