# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
    - $HOME/bin

script:
  - "Rscript -e 'blogdown::install_hugo()'"
  - "Rscript -e 'blogdown::build_site()'"

after_success:
  - ./deploy.sh
