
language: r
sudo: true
cache:
  packages: true
  directories:
    - $HOME/bin

before_install:
  - sudo apt-get install -y fonts-roboto libgeos-dev libgdal-dev libudunits2-dev
  - fc-cache -fv

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'hrbrthemes::import_roboto_condensed()'
  - Rscript -e 'blogdown::build_site()'

after_success:
  - ./deploy.sh
